version: 2.0

# heavily inspired by:
# https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-v2-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install libsnappy-dev
        command: sudo apt install -y libsnappy-dev
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
          - .pytest_cache/v/eth2/bls/key-cache
        key: cache-v2-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

eth2_fixtures: &eth2_fixtures
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-v4-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}-{{ checksum "./.circleci/get_eth2_fixtures.sh" }}
    - run:
        name: install libsnappy-dev
        command: sudo apt install -y libsnappy-dev
    - run:
        name: download the required yaml files if missing
        command: ./.circleci/get_eth2_fixtures.sh
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
          - .pytest_cache/v/eth2/bls/key-cache
          - ./eth2-fixtures
        key: cache-v4-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}-{{ checksum "./.circleci/get_eth2_fixtures.sh" }}
jobs:
  py311-lint:
    <<: *common
    docker:
      - image: cimg/python:3.11
        environment:
          TOXENV: py311-lint
  py310-lint:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-lint

  py312-eth2-core:
    <<: *common
    docker:
      - image: cimg/python:3.12
        environment:
          TOXENV: py312-eth2-core
  py311-eth2-core:
    <<: *common
    docker:
      - image: cimg/python:3.11
        environment:
          TOXENV: py311-eth2-core
  py310-eth2-core:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-core

  py310-eth2-utils:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-utils
  py310-eth2-fixtures:
    <<: *eth2_fixtures
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-fixtures
  py310-eth2-integration:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-integration
  py310-eth2-trio:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-trio
  py310-eth2-components:
    <<: *common
    docker:
      - image: cimg/python:3.10
        environment:
          TOXENV: py310-eth2-components

  docker-trinity-beacon-image-build-test:
    machine: true
    steps:
      - checkout
      - run: docker build -t ethereum/trinity-beacon:test-build -f ./docker/Dockerfile .
      - run: docker run ethereum/trinity-beacon:test-build --help

workflows:
  version: 2
  test:
    jobs:
      # These tests are long, so should be started first to optimize for total suite run time
      - py312-eth2-core
      - py311-eth2-core
      - py310-eth2-core

      - py310-eth2-utils
      - py310-eth2-fixtures
      - py310-eth2-integration
      - py310-eth2-components
      - py310-eth2-trio

      - py311-lint
      - py310-lint

      - docker-trinity-beacon-image-build-test
